### ISSUE TITLE
OpenStack CPI should error when multiple security groups match and hint to using UUIDs

### ISSUE THREAD

**Issue by benschweizer** [cloudfoundry/bosh-openstack-cpi-release#231]
When multiple security groups with the same name exist, bosh create-env fails.
The function ```find_openstack_sg_by_name``` returns the first uuid from a list, which is most likely wrong. The openstack cli tool in contrast raises an error "More than one SecurityGroup exists with the name 'bosh'"; I think the cpi should behave the same.

**Comment by voelzmo** [comment]
That's a good point, @benschweizer, thanks!

For the time being, you can use the `UUID` instead of the `name` for a security group reference, in case that unblocks you in your current environment. This was implemented as a follow up of https://github.com/cloudfoundry/bosh-openstack-cpi-release/pull/117 – but apparently not documented.

**Comment by voelzmo** [comment]
Changed the title to match criteria for a possible solution
